import { EventType, TimelineEventItem } from "../components/TimelineEvent/TimelineEvent";
import {v4 as uuidv4} from 'uuid';
import React from "react";
import moment from "moment";

export const EVENTS: TimelineEventItem[] = [
    {
        id: uuidv4(),
        title: 'Spoke at ct\'webdev',
        description: <p>Keynoted Day 2 <a>"The Way We Think About Change"</a>, with <a>slides</a>.</p>, 
        date: moment("2020-02-01").toDate(),
        type: EventType.SPEAKING,
    },
    {
        id: uuidv4(),
        title: 'Mentored at Global Diversity CFP Date Seattle',
        description: <p>Led small breakout sessions covering coming up with talk topics, writing CFPs, and addressing inclusion within the conference and speaker community. Spoke in a panel about my experience becoming a speaker.</p>, 
        date: moment("2020-01-01").toDate(),
        type: EventType.COMMUNITY,
    },
    {
        id: uuidv4(),
        title: 'Spoke at CascadiaJS',
        description: <p>Presented <a>"Creative Coding: Making Reusable SVGs with React"</a> to over 800 attendees, with <a>slides</a> and <a>code</a>.</p>, 
        date: moment("2019-11-01").toDate(),
        type: EventType.SPEAKING,
    },
    {
        id: uuidv4(),
        title: 'Spoke at NordicJS',
        description: <p>Presented <a>"Localization: Implementing and Testing... Locally"</a> to over 1200 attendees, with <a>slides</a> and <a>recording</a>.</p>, 
        date: moment("2019-10-01").toDate(),
        type: EventType.SPEAKING,
    },
    {
        id: uuidv4(),
        title: 'Spoke at Chicago JSCamp',
        description: <p>Presented <a>"The Startup's Guide to Creating a Design System"</a> to over 150 attendees, with <a>slides</a> and <a>recording</a>.</p>, 
        date: moment("2019-10-01").toDate(),
        type: EventType.SPEAKING,
    },
    {
        id: uuidv4(),
        title: 'Spoke at cKeys Seattle Keyboard Meetup',
        description: <p>Presented <a>"Anatomy of a Mechanical Keyboard"</a> to over 300 attendees, with <a>slides</a>.</p>, 
        date: moment("2019-07-01").toDate(),
        type: EventType.SPEAKING,
    },
    {
        id: uuidv4(),
        title: 'Joined CedarAI',
        description: <p>As senior UX engineer, I'm responsible for creating and maintaining the products' design systems, engaging with customers on-site, and coding frontend features.</p>, 
        date: moment("2019-07-01").toDate(),
        type: EventType.NEW,
    },
    {
        id: uuidv4(),
        title: 'Left Microsoft',
        description: <p>After nearly three years at Microsoft, it was time to try something new! Before starting my new role, I took some time off to travel the world.</p>, 
        date: moment("2019-05-01").toDate(),
        type: EventType.NEW,
    },
    {
        id: uuidv4(),
        title: 'Spoke at Seattle ReactJS Meetup',
        description: <p>Presented <a>"A/B Testing in React"</a> to 140 attendees, with <a>slides</a>, <a>recording</a>, and <a>code</a>.</p>, 
        date: moment("2019-03-01").toDate(),
        type: EventType.SPEAKING,
    },
    {
        id: uuidv4(),
        title: 'Spoke & mentored at KnightHacks',
        description: <p>Represented Microsoft, presented <a>"Azure Functions & Cognitive Services"</a>, and helped hackers with technical questions during <a>the hackathon</a>.</p>, 
        date: moment("2019-03-01").toDate(),
        type: EventType.SPEAKING,
    },
    {
        id: uuidv4(),
        title: 'Spoke at Seattle Web App Developers Group Meetup',
        description: <p>Presented "A/B Testing in React" to 80 attendees, with slides, recording, and code.</p>, 
        date: moment("2019-01-01").toDate(),
        type: EventType.SPEAKING,
    },
    {
        id: uuidv4(),
        title: 'Mentored at Hack//WA',
        description: <p>Represented Microsoft and helped hackers with technical questions during the hackathon.</p>, 
        date: moment("2019-01-01").toDate(),
        type: EventType.COMMUNITY,
    },
    {
        id: uuidv4(),
        title: 'Mentored at ShellHacks',
        description: <p>Gave various workshops, including "Static Website Deployment in Azure" and "Demystifying the Tech Interview".</p>, 
        date: moment("2018-09-01").toDate(),
        type: EventType.COMMUNITY,
    },
    {
        id: uuidv4(),
        title: 'Spoke at Seattle Keyboard Meetup',
        description: <p>"Anatomy of a Mechanical Keyboard", later featured on Massdrop.</p>, 
        date: moment("2018-07-01").toDate(),
        type: EventType.SPEAKING,
    },
    {
        id: uuidv4(),
        title: 'Started Masters Program',
        description: <p>Pursuing my Masters in Human Computer Interaction at Iowa State University while working full time.</p>, 
        date: moment("2018-01-01").toDate(),
        type: EventType.SCHOOL,
    },
    {
        id: uuidv4(),
        title: 'Joined Microsoft',
        description: <p>Fresh out of college, I started on the Microsoft Edge team. Currently a Software Engineer 2, I work closely with designers and PMs to take a feature idea through ideation, mockups, user studies, and development.</p>, 
        date: moment("2016-08-01").toDate(),
        type: EventType.NEW,
    },
    {
        id: uuidv4(),
        title: 'Graduated from University of Central Florida',
        description: <p>Graduated with a Bachelors in Computer Science.</p>, 
        date: moment("2016-05-01").toDate(),
        type: EventType.SCHOOL,
    },
    {
        id: uuidv4(),
        title: 'Interned at Salesforce',
        description: <p>Built fit-and-finish UI and decided backend work was not for me.</p>, 
        date: moment("2015-05-01").toDate(),
        type: EventType.NEW,
    },
    {
        id: uuidv4(),
        title: 'Joined SavvySuit',
        description: <p>First (and only) frontend developer at Orlando legal startup. Part of Starter Studio's fourth accelerator class. Created mockups, ran user studies, developed client-side Chrome app.</p>, 
        date: moment("2015-01-01").toDate(),
        type: EventType.NEW,
    },
    {
        id: uuidv4(),
        title: 'Interned at Google',
        description: <p>Developed campaign stats UI for Google AdWords Android app.</p>, 
        date: moment("2014-05-01").toDate(),
        type: EventType.NEW,
    },
    {
        id: uuidv4(),
        title: 'Joined UCF programming team',
        description: <p>First all-women programming team and placed third in the senior division at my first competition.</p>, 
        date: moment("2013-01-01").toDate(),
        type: EventType.NEW,
    },
]