import { EventType, TimelineEventItem } from "../components/TimelineEvent/TimelineEvent";
import {v4 as uuidv4} from 'uuid';
import React from "react";
import moment from "moment";

export const EVENTS: TimelineEventItem[] = [
    {
        id: uuidv4(),
        title: 'Mentor in Microsoft LEAP program',
        description: <p>Mentor apprentice in LEAP program as they learn technical skills to transition into a software development career</p>, 
        date: moment("2021-07-01").toDate(),
        type: EventType.COMMUNITY,
    },
    {
        id: uuidv4(),
        title: 'Joined Microsoft',
        description: <p>So nice, I was hired twice 😊 I lead a team of awesome frontend engineers building Bing At Work, Microsoft's enterprise search.</p>, 
        date: moment("2020-12-01").toDate(),
        type: EventType.NEW,
    },
    {
        id: uuidv4(),
        title: 'Left CedarAI',
        description: <p>After a growing my knowledge in design and leading a frontend team, I decided to move back to a large company where I could narrow my scope of work and direct my full attention to frontend and leading a great team.</p>, 
        date: moment("2020-10-01").toDate(),
        type: EventType.NEW,
    },
    {
        id: uuidv4(),
        title: 'Spoke at ct\'webdev',
        description: <><p>Keynoted Day 2 <a href="https://github.com/isabelacmor/talks/blob/master/the-way-we-think-about-change.md" target="_blank">"The Way We Think About Change"</a>, with <a href="https://github.com/isabelacmor/talks/blob/master/slides/TheWayWeThinkAboutChange.pdf" target="_blank">slides</a>.</p><p>Presented session <a href="https://github.com/isabelacmor/talks/blob/master/building-empathy-and-accessible-apps.md" target="_blank">Building empathy and accessible apps"</a>, with <a href="https://github.com/isabelacmor/talks/blob/master/slides/BuildingEmpathy.pdf" target="_blank">slides</a>.</p></>, 
        date: moment("2020-02-01").toDate(),
        type: EventType.SPEAKING,
    },
    {
        id: uuidv4(),
        title: 'Mentored at Global Diversity CFP Date Seattle',
        description: <p>Led small breakout sessions covering coming up with talk topics, writing CFPs, and addressing inclusion within the conference and speaker community. Spoke in a panel about my experience becoming a speaker.</p>, 
        date: moment("2020-01-01").toDate(),
        type: EventType.COMMUNITY,
    },
    {
        id: uuidv4(),
        title: 'Spoke at CascadiaJS',
        description: <p>Presented <a href="https://github.com/isabelacmor/talks/blob/master/making-reusable-svgs-with-react.md" target="_blank">"Creative Coding: Making Reusable SVGs with React"</a> to over 800 attendees, with <a href="https://github.com/isabelacmor/talks/blob/master/slides/ReusableSVGs.pdf" target="_blank">slides</a> and <a href="https://github.com/isabelacmor/svgrobots" target="_blank">code</a>.</p>, 
        date: moment("2019-11-01").toDate(),
        type: EventType.SPEAKING,
    },
    {
        id: uuidv4(),
        title: 'Spoke at NordicJS',
        description: <p>Presented <a href="https://github.com/isabelacmor/talks/blob/master/localization-implementation-and-testing.md" target="_blank">"Localization: Implementing and Testing... Locally"</a> to over 1200 attendees, with <a href="https://github.com/isabelacmor/talks/blob/master/slides/LocalizationImplementationAndTesting.pdf" target="_blank">slides</a> and <a href="https://www.youtube.com/watch?v=mh_Ck6Snoyw&list=PLGP3VO5jDf8x0gh5H7dZ41F0nVDlwDMuy&index=6" target="_blank">recording</a>.</p>, 
        date: moment("2019-10-01").toDate(),
        type: EventType.SPEAKING,
    },
    {
        id: uuidv4(),
        title: 'Spoke at Chicago JSCamp',
        description: <p>Presented <a href="https://github.com/isabelacmor/talks/blob/master/startups-guide-to-creating-a-design-system.md" target="_blank">"The Startup's Guide to Creating a Design System"</a> to over 150 attendees, with <a href="https://github.com/isabelacmor/talks/blob/master/slides/StartupsGuideToCreatingDesignSystem.pdf" target="_blank">slides</a> and <a href="https://www.youtube.com/watch?v=OE5UxUiRfvo" target="_blank">recording</a>.</p>, 
        date: moment("2019-10-01").toDate(),
        type: EventType.SPEAKING,
    },
    {
        id: uuidv4(),
        title: 'Spoke at cKeys Seattle Keyboard Meetup',
        description: <p>Presented <a href="https://ckeys.org/events/smkmeetup/#presentations" target="_blank">"Anatomy of a Mechanical Keyboard"</a> to over 300 attendees, with <a href="https://github.com/isabelacmor/talks/blob/master/slides/AnatomyOfMechanicalKeyboard.pdf" target="_blank">slides</a>.</p>, 
        date: moment("2019-07-01").toDate(),
        type: EventType.SPEAKING,
    },
    {
        id: uuidv4(),
        title: 'Joined CedarAI',
        description: <p>As senior UX engineer, I'm responsible for creating and maintaining the products' design systems, engaging with customers on-site, and coding frontend features.</p>, 
        date: moment("2019-07-01").toDate(),
        type: EventType.NEW,
    },
    {
        id: uuidv4(),
        title: 'Left Microsoft',
        description: <p>After nearly three years at Microsoft, it was time to try something new! Before starting my new role, I took some time off to travel the world.</p>, 
        date: moment("2019-05-01").toDate(),
        type: EventType.NEW,
    },
    {
        id: uuidv4(),
        title: 'Spoke at Seattle ReactJS Meetup',
        description: <p>Presented <a href="https://www.meetup.com/seattle-react-js/events/259175585/" target="_blank">"A/B Testing in React"</a> to 140 attendees, with <a href="https://www.slideshare.net/IsabelaMoreira21/ab-testing-with-react" target="_blank">slides</a>, <a href="https://www.youtube.com/watch?v=FsKlL8EE9pQ" target="_blank">recording</a>, and <a href="https://github.com/isabelacmor/ab-testing-react" target="_blank">code</a>.</p>, 
        date: moment("2019-03-01").toDate(),
        type: EventType.SPEAKING,
    },
    {
        id: uuidv4(),
        title: 'Spoke & mentored at KnightHacks',
        description: <p>Represented Microsoft, presented <a href="https://github.com/TylerLeonhardt/AzureFunctions-CognitiveServices-FaceEmotion-Demo" target="_blank">"Azure Functions & Cognitive Services"</a>, and helped hackers with technical questions during <a href="https://knighthacks.org/" target="_blank">the hackathon</a>.</p>, 
        date: moment("2019-03-01").toDate(),
        type: EventType.SPEAKING,
    },
    {
        id: uuidv4(),
        title: 'Spoke at Seattle Web App Developers Group Meetup',
        description: <p>Presented <a href="https://www.meetup.com/Seattle-Web-App-Developers-Group/events/257189459/" target="_blank">"A/B Testing in React"</a> to 80 attendees, with <a href="https://www.slideshare.net/IsabelaMoreira21/ab-testing-with-react" target="_blank">slides</a>, <a href="https://www.youtube.com/watch?v=FsKlL8EE9pQ" target="_blank">recording</a>, and <a href="https://github.com/isabelacmor/ab-testing-react" target="_blank">code</a>.</p>, 
        date: moment("2019-01-01").toDate(),
        type: EventType.SPEAKING,
    },
    {
        id: uuidv4(),
        title: 'Mentored at Hack//WA',
        description: <p>Represented Microsoft and helped hackers with technical questions during <a href="http://www.hackwashingtonstate.com/" target="_blank">the hackathon</a>.</p>, 
        date: moment("2019-01-01").toDate(),
        type: EventType.COMMUNITY,
    },
    {
        id: uuidv4(),
        title: 'Mentored at ShellHacks',
        description: <p>Gave various workshops, including "Static Website Deployment in Azure" and <a href="https://github.com/isabelacmor/fiu-interviewprep" target="_blank">"Demystifying the Tech Interview"</a>.</p>, 
        date: moment("2018-09-01").toDate(),
        type: EventType.COMMUNITY,
    },
    {
        id: uuidv4(),
        title: 'Spoke at Seattle Keyboard Meetup',
        description: <p><a href="https://ckeys.org/events/smkmeetup/#presentations" target="_blank">"Anatomy of a Mechanical Keyboard"</a>, later <a href="https://www.massdrop.com/talk/10016/anatomy-of-a-mechanical-keyboard" target="_blank">featured on Massdrop</a>.</p>, 
        date: moment("2018-07-01").toDate(),
        type: EventType.SPEAKING,
    },
    {
        id: uuidv4(),
        title: 'Started Masters Program',
        description: <p>Pursuing my Masters in Human Computer Interaction at Iowa State University while working full time.</p>, 
        date: moment("2018-01-01").toDate(),
        type: EventType.SCHOOL,
    },
    {
        id: uuidv4(),
        title: 'Joined Microsoft',
        description: <p>Fresh out of college, I started on the Microsoft Edge team. Currently a Software Engineer 2, I work closely with designers and PMs to take a feature idea through ideation, mockups, user studies, and development.</p>, 
        date: moment("2016-08-01").toDate(),
        type: EventType.NEW,
    },
    {
        id: uuidv4(),
        title: 'Graduated from University of Central Florida',
        description: <p>Graduated with a Bachelors in Computer Science.</p>, 
        date: moment("2016-05-01").toDate(),
        type: EventType.SCHOOL,
    },
    {
        id: uuidv4(),
        title: 'Interned at Salesforce',
        description: <p>Built fit-and-finish UI and decided backend work was not for me.</p>, 
        date: moment("2015-05-01").toDate(),
        type: EventType.NEW,
    },
    {
        id: uuidv4(),
        title: 'Joined SavvySuit',
        description: <p>First (and only) frontend developer at Orlando legal startup. Part of <a href="https://www.orlandosentinel.com/business/technology/tech_check/os-starter-studio-fourth-class-debut-20150713-post.html" target="_blank">Starter Studio's fourth accelerator class</a>. Created mockups, ran user studies, developed client-side Chrome app.</p>, 
        date: moment("2015-01-01").toDate(),
        type: EventType.NEW,
    },
    {
        id: uuidv4(),
        title: 'Interned at Google',
        description: <p>Developed campaign stats UI for <a href="https://play.google.com/store/apps/details?id=com.google.android.apps.adwords&hl=en_US" target="_blank">Google AdWords Android app</a>.</p>, 
        date: moment("2014-05-01").toDate(),
        type: EventType.NEW,
    },
    {
        id: uuidv4(),
        title: 'Joined UCF programming team',
        description: <p>First <a href="https://today.ucf.edu/ucf-sends-first-all-female-team-to-super-bowl-of-programming/" target="_blank">all-women programming team</a> and placed third in the senior division at my first competition.</p>, 
        date: moment("2013-01-01").toDate(),
        type: EventType.NEW,
    },
]